export const factions = [
  {value: 'COSMIC', label: "cosmic"},
  {value: 'VOID', label: "void"},
  {value: 'GALACTIC', label: "galactic"},
  {value: 'QUANTUM', label: "quantum"},
  {value: 'DOMINION', label: "dominion"},
  {value: 'ASTRO', label: "astro"},
  {value: 'CORSAIRS', label: "corsairs"},
  {value: 'OBSIDIAN', label: "obsidian"},
  {value: 'AEGIS', label: "aegis"},
  {value: 'UNITED', label: "united"},
  {value: 'SOLITARY', label: "solitary"},
  {value: 'COBALT', label: "cobalt"},
  {value: 'OMEGA', label: "omega"},
  {value: 'ECHO', label: "echo"},
  {value: 'LORDS', label: "lords"},
  {value: 'CULT', label: "cult"},
  {value: 'ANCIENTS', label: "ancients"},
  {value: 'SHADOW', label: "shadow"},
  {value: 'ETHEREAL', label: "ethereal"}
];

export const traits = [
  {value: 'UNDER_CONSTRUCTION', label: 'Under Construction'},
  {value: 'MARKETPLACE', label: 'Marketplace'},
  {value: 'SHIPYARD', label: 'Shipyard'},
  {value: 'OUTPOST', label: 'Outpost'},
  {value: 'SCATTERED_SETTLEMENTS', label: 'Scattered Settlements'},
  {value: 'SPRAWLING_CITIES', label: 'Sprawling Cities'},
  {value: 'MEGA_STRUCTURES', label: 'Mega Structures'},
  {value: 'PIRATE_BASE', label: 'Pirate Base'},
  {value: 'OVERCROWDED', label: 'Overcrowded'},
  {value: 'HIGH_TECH', label: 'High Tech'},
  {value: 'CORRUPT', label: 'Corrupt'},
  {value: 'BUREAUCRATIC', label: 'Bureaucratic'},
  {value: 'TRADING_HUB', label: 'Trading Hub'},
  {value: 'INDUSTRIAL', label: 'Industrial'},
  {value: 'BLACK_MARKET', label: 'Black Market'},
  {value: 'RESEARCH_FACILITY', label: 'Research Facility'},
  {value: 'MILITARY_BASE', label: 'Military Base'},
  {value: 'SURVEILLANCE_OUTPOST', label: 'Surveillance Outpost'},
  {value: 'EXPLORATION_OUTPOST', label: 'Exploration Outpost'},
  {value: 'MINERAL_DEPOSITS', label: 'Mineral Deposits'},
  {value: 'COMMON_METAL_DEPOSITS', label: 'Common Metal Deposits'},
  {value: 'PRECIOUS_METAL_DEPOSITS', label: 'Precious Metal Deposits'},
  {value: 'RARE_METAL_DEPOSITS', label: 'Rare Metal Deposits'},
  {value: 'METHANE_POOLS', label: 'Methane Pools'},
  {value: 'ICE_CRYSTALS', label: 'Ice Crystals'},
  {value: 'EXPLOSIVE_GASES', label: 'Explosive Gases'},
  {value: 'STRONG_MAGNETOSPHERE', label: 'Strong Magnetosphere'},
  {value: 'VIBRANT_AURORAS', label: 'Vibrant Auroras'},
  {value: 'SALT_FLATS', label: 'Salt Flats'},
  {value: 'CANYONS', label: 'Canyons'},
  {value: 'PERPETUAL_DAYLIGHT', label: 'Perpetual Daylight'},
  {value: 'PERPETUAL_OVERCAST', label: 'Perpetual Overcast'},
  {value: 'DRY_SEABEDS', label: 'Dry Seabeds'},
  {value: 'MAGMA_SEAS', label: 'Magma Seas'},
  {value: 'SUPERVOLCANOES', label: 'Supervolcanoes'},
  {value: 'ASH_CLOUDS', label: 'Ash Clouds'},
  {value: 'VAST_RUINS', label: 'Vast Ruins'},
  {value: 'MUTATED_FLORA', label: 'Mutated Flora'},
  {value: 'TERRAFORMED', label: 'Terraformed'},
  {value: 'EXTREME_TEMPERATURES', label: 'Extreme Temperatures'},
  {value: 'EXTREME_PRESSURE', label: 'Extreme Pressure'},
  {value: 'DIVERSE_LIFE', label: 'Diverse Life'},
  {value: 'SCARCE_LIFE', label: 'Scarce Life'},
  {value: 'FOSSILS', label: 'Fossils'},
  {value: 'WEAK_GRAVITY', label: 'Weak Gravity'},
  {value: 'STRONG_GRAVITY', label: 'Strong Gravity'},
  {value: 'CRUSHING_GRAVITY', label: 'Crushing Gravity'},
  {value: 'TOXIC_ATMOSPHERE', label: 'Toxic Atmosphere'},
  {value: 'CORROSIVE_ATMOSPHERE', label: 'Corrosive Atmosphere'},
  {value: 'BREATHABLE_ATMOSPHERE', label: 'Breathable Atmosphere'},
  {value: 'THIN_ATMOSPHERE', label: 'Thin Atmosphere'},
  {value: 'JOVIAN', label: 'Jovian'},
  {value: 'ROCKY', label: 'Rocky'},
  {value: 'VOLCANIC', label: 'Volcanic'},
  {value: 'FROZEN', label: 'Frozen'},
  {value: 'SWAMP', label: 'Swamp'},
  {value: 'BARREN', label: 'Barren'},
  {value: 'TEMPERATE', label: 'Temperate'},
  {value: 'JUNGLE', label: 'Jungle'},
  {value: 'OCEAN', label: 'Ocean'},
  {value: 'RADIOACTIVE', label: 'Radioactive'},
  {value: 'MICRO_GRAVITY_ANOMALIES', label: 'Micro Gravity Anomalies'},
  {value: 'DEBRIS_CLUSTER', label: 'Debris Cluster'},
  {value: 'DEEP_CRATERS', label: 'Deep Craters'},
  {value: 'SHALLOW_CRATERS', label: 'Shallow Craters'},
  {value: 'UNSTABLE_COMPOSITION', label: 'Unstable Composition'},
  {value: 'HOLLOWED_INTERIOR', label: 'Hollowed Interior'},
  {value: 'STRIPPED', label: 'Stripped'}
];

export const waypointTypes = [
  {value: 'PLANET', label: 'Planet'},
  {value: 'GAS_GIANT', label: 'Gas Giant'},
  {value: 'MOON', label: 'Moon'},
  {value: 'ORBITAL_STATION', label: 'Orbital Station'},
  {value: 'JUMP_GATE', label: 'Jump Gate'},
  {value: 'ASTEROID_FIELD', label: 'Asteroid Field'},
  {value: 'ASTEROID', label: 'Asteroid'},
  {value: 'ENGINEERED_ASTEROID', label: 'Engineered Asteroid'},
  {value: 'ASTEROID_BASE', label: 'Asteroid Base'},
  {value: 'NEBULA', label: 'Nebula'},
  {value: 'DEBRIS_FIELD', label: 'Debris Field'},
  {value: 'GRAVITY_WELL', label: 'Gravity Well'},
  {value: 'ARTIFICIAL_GRAVITY_WELL', label: 'Artificial Gravity Well'},
  {value: 'FUEL_STATION', label: 'Fuel Station'}
];
